<a href="https://colab.research.google.com/github/JanuarLum/daa2/blob/main/DAA3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DAA 19 Sept 21

In [101]:
import numpy as np

In [2]:
#List
aList = ["John",33,"Toronto",True]
print(aList)

['John', 33, 'Toronto', True]


In [9]:
aList = ["Januar",2020071003,"Informatika","Desain dan Analisis Algoritma","15-09-2021","Universitas Pembangunan Jaya"]
print(aList)

['Januar', 2020071003, 'Informatika', 'Desain dan Analisis Algoritma', '15-09-2021', 'Universitas Pembangunan Jaya']


In [12]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[1]

'Green'

In [31]:
#Tuple
bin_name=['Januar Putra']
for Mahasiswa in bin_name:
  print("UPJ " + Mahasiswa)

UPJ Januar Putra


In [35]:
bin_colors=['Red','Green','Blue','Yellow']
for aColor in bin_colors:
  print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [43]:
bin_UPJ=['Universitas','Pembangunan','Jaya']
bin_UPJ

['Universitas', 'Pembangunan', 'Jaya']

In [56]:
#Nested Tuple
nested_tuple = ([100],[200,400,600],[300],[400,800])
print(nested_tuple[2])

[300]


In [57]:
#Dictonary
bin_colors={
    "manual_color":"Yellow",
    "aprroved_color":"Green",
    "refused_color":"Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'aprroved_color': 'Green', 'refused_color': 'Red'}


In [58]:
bin_colors.get('aprroved_color')

'Green'

In [59]:
bin_colors['aprroved_color']

'Green'

In [60]:
bin_colors['aprroved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'aprroved_color': 'Purple', 'refused_color': 'Red'}


In [62]:
latihan={
    "Nama":"Januar Putra",
    "NIM":"2020071003",
    "Prodi":"Informatika",
    "Universitas":"UPJ"
}
print(latihan)

{'Nama': 'Januar Putra', 'NIM': '2020071003', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [69]:
#Sets
green = {'grass','leaves','tree'}
print(green)

{'leaves', 'grass', 'tree'}


In [73]:
yellow = {'blood','leaves','fire hydrant','rose'}
red = {'dandelions','fire hydrant','leaves'}
print(yellow|red)
print(yellow&red)

{'leaves', 'dandelions', 'blood', 'fire hydrant', 'rose'}
{'leaves', 'fire hydrant'}


In [94]:
#DataFrames
import pandas as pd
df=pd.DataFrame([
                 ['1','Fares',32,True],
                 ['2','Elena',23,False],
                 ['3','Steven',40,True]])
df.columns = ['id','name','age','decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [91]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [92]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [99]:
import pandas as pd
df=pd.DataFrame([
                 ['1','Informatika',50,30,20],
                 ['2','Sistem Informasi',55,30,25],
                 ['3','Teknik Sipil',40,30,10]])
df.columns = ['No','Prodi','Mahasiswa','Laki-laki','Perempuan']
df

No             Prodi  Mahasiswa  Laki-laki  Perempuan
0  1       Informatika         50         30         20
1  2  Sistem Informasi         55         30         25
2  3      Teknik Sipil         40         30         10

In [102]:
myMatrix=np.array([[11,12,13],[21,22,23],[31,32,33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [103]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [138]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-I]
  def size(self):
    return len(self.items)

In [142]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

print(stack.pop())

print(stack.isEmpty())

Yellow
False


In [147]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

In [148]:
queue=Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())

4


In [149]:
print(queue.dequeue())
print(queue.dequeue())

Red
Green
